services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: radish_miyazaki
      POSTGRES_PASSWORD: gallery_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: picture_gallery
    restart: always
volumes:
  data:

